version: "3.9"

services:
  
  bot:
    build:
      context: .
      dockerfile: ./bot/build/Dockerfile
    env_file: .env
    depends_on:
      - mongo
  
  scraper:
    build:
      context: .
      dockerfile: ./scraper/build/Dockerfile
    env_file: .env
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    restart: always
    volumes:
      - "/home/david/dev/staging/super-j-bot/data/db:/data/db"
    ports:
      - 27017:27017

      